In [3]:
import numpy as np
random_arr=np.random.default_rng(12345).random(10)
random_arr

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [8]:
random_normal=np.random.default_rng(12345).normal(5,1,10) #mean,stddev,size
random_normal

array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

In [10]:
random_integers=np.random.default_rng(12345).integers(0,10,100)
random_integers

array([6, 2, 7, 3, 2, 7, 6, 6, 9, 3, 8, 3, 5, 5, 2, 1, 2, 6, 6, 9, 7, 2,
       9, 9, 7, 6, 1, 0, 2, 4, 0, 8, 4, 6, 2, 3, 1, 7, 7, 2, 7, 0, 3, 1,
       7, 3, 4, 4, 4, 2, 5, 8, 4, 1, 0, 1, 0, 0, 1, 5, 8, 8, 6, 6, 3, 9,
       6, 7, 7, 8, 7, 9, 5, 5, 2, 9, 5, 4, 3, 2, 6, 4, 5, 6, 8, 3, 6, 9,
       4, 2, 2, 3, 6, 2, 8, 3, 0, 0, 0, 6], dtype=int64)

In [13]:
import pandas as pd
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(states, index=states)
obj4

California    California
Ohio                Ohio
Oregon            Oregon
Texas              Texas
dtype: object

In [16]:
obj4.iloc[0]=np.nan


In [17]:
obj4

California       NaN
Ohio            Ohio
Oregon        Oregon
Texas          Texas
dtype: object

In [23]:
obj4[pd.isnull(obj4)==False]

Ohio        Ohio
Oregon    Oregon
Texas      Texas
dtype: object

In [28]:
ser1=pd.Series(np.arange(1,100,10),index=np.arange(10,20))
ser1

10     1
11    11
12    21
13    31
14    41
15    51
16    61
17    71
18    81
19    91
dtype: int32

In [31]:
arr1=np.random.randint(1,100,size=(3,5))

In [32]:
arr1.astype('float')

array([[50.,  8., 19., 97., 48.],
       [89., 77.,  6., 70., 22.],
       [46., 82., 72., 13., 60.]])

In [33]:
arr1=arr1.astype('float')

In [34]:
ser1.values

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [36]:
ser1.values

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [37]:
ser1.max()

91

In [38]:
ser1.min()

1

In [39]:
ser1.mean()

46.0

In [40]:
ser1.product()

-1120375461

In [41]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
#If the nested dict is passed to the DataFrame, pandas will interpret the outer dict keys
#as the columns and the inner keys as the row indices:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [45]:
pd.DataFrame(pop, index=[2001, 2002, 2003])
pdata = {'Ohio': frame3['Ohio'][:3],'Nevada': frame3['Nevada'][:3]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2000   1.5     NaN

In [51]:
ser1 = pd.Series([1,2,3,4], index = ['A','B','C','D'])
ser1   

A    1
B    2
C    3
D    4
dtype: int64

In [48]:
ser2 = ser1.reindex(['A','B','C','D','E','F'])
ser2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [49]:
ser2.reindex(['A','B','C','D','E','F','G'], fill_value = 0)

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
G    0.0
dtype: float64

In [50]:
ser2.reindex(range(15),fill_value=0)

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
dtype: float64

In [55]:
ser3 = pd.Series(['USA','Mexico','Canada'], index = [0,5,10])
ser3

0        USA
5     Mexico
10    Canada
dtype: object

In [60]:
ser3=ser3.reindex(range(15),method='ffill')

In [61]:
ser3

0        USA
1        USA
2        USA
3        USA
4        USA
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14    Canada
dtype: object

In [62]:
ser3[::2]

0        USA
2        USA
4        USA
6     Mexico
8     Mexico
10    Canada
12    Canada
14    Canada
dtype: object

In [63]:
ser3[::2]=np.nan


In [64]:
ser3

0        NaN
1        USA
2        NaN
3        USA
4        NaN
5     Mexico
6        NaN
7     Mexico
8        NaN
9     Mexico
10       NaN
11    Canada
12       NaN
13    Canada
14       NaN
dtype: object

In [65]:
ser3.dropna()

1        USA
3        USA
5     Mexico
7     Mexico
9     Mexico
11    Canada
13    Canada
dtype: object

In [66]:
ser3.fillna(method='bfill')

C:\Users\Kevin\AppData\Local\Temp\ipykernel_14108\765074465.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ser3.fillna(method='bfill')


0        USA
1        USA
2        USA
3        USA
4     Mexico
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14       NaN
dtype: object

In [67]:
ser3

0        NaN
1        USA
2        NaN
3        USA
4        NaN
5     Mexico
6        NaN
7     Mexico
8        NaN
9     Mexico
10       NaN
11    Canada
12       NaN
13    Canada
14       NaN
dtype: object

In [68]:
ser3.bfill()

0        USA
1        USA
2        USA
3        USA
4     Mexico
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14       NaN
dtype: object

In [69]:
ser3.fillna("500")

0        500
1        USA
2        500
3        USA
4        500
5     Mexico
6        500
7     Mexico
8        500
9     Mexico
10       500
11    Canada
12       500
13    Canada
14       500
dtype: object

In [70]:
ser3.fillna(500)

0        500
1        USA
2        500
3        USA
4        500
5     Mexico
6        500
7     Mexico
8        500
9     Mexico
10       500
11    Canada
12       500
13    Canada
14       500
dtype: object

In [76]:
type(ser3)

pandas.core.series.Series

In [78]:
dframe1 = pd.DataFrame(np.arange(9).reshape(3,3), index =['SF','LA','NY'], 
                    columns = ['pop','size','year'])
dframe1

pop  size  year
SF    0     1     2
LA    3     4     5
NY    6     7     8

In [79]:
dframe1.drop('LA')

pop  size  year
SF    0     1     2
NY    6     7     8

In [80]:
dframe2 = dframe1.drop('LA', axis=0)
dframe2

pop  size  year
SF    0     1     2
NY    6     7     8

In [81]:
dframe1
dframe1.drop('year', axis =1)

pop  size
SF    0     1
LA    3     4
NY    6     7

In [86]:
df1=pd.DataFrame(np.random.randint(1,100,(20,10)))
df1

0   1   2   3   4   5   6   7   8   9
0   48  69  20  29  35  44  38  50  83  48
1   33  19  31  42  54  42  46  27  95  50
2    1   4  39  77  88  53  76   5  55  87
3   33  71  21  55   7  20  50  34  71  92
4   23  41  36  29  96  44  34  44  72  26
5   27  54  50  38  50  90  48  95  60  71
6   41  61  88  16   3  90  27   1  98  25
7   84  39  55  85  69  72  36  90  80  13
8   53  14   5   3  86  86  41  89  88  94
9   84  92  32  77  95  74  90  85  76  53
10  55  96  35  96  38  26  54  31  52  99
11  28  54  15  58  85  63  64  83  53  77
12  15  28  90  49  30  95  87  90   5  42
13  32  97  79  60  41  16  31  26  43  41
14  39  79  99   6  73  92  18  21   9  15
15  68  95  69  45  10  12   4  57  41  10
16  55  76  69  71  44  97  22  32  59  19
17  63   8  68  50  12  89  57  35  69  95
18  13  25  10  84  11  54  34  41  13  17
19  69  86  73  23  85  51  94   1  93  96

In [97]:
import random
nacount=int(df1.size*.25)
for x in range(nacount):
    df1.iloc[random.randrange(df1.shape[0]),random.randrange(df1.shape[1])]=np.nan
df1

0     1     2     3     4     5     6     7     8     9
0   48.0   NaN  20.0  29.0  35.0  44.0  38.0  50.0  83.0   NaN
1    NaN  19.0  31.0  42.0  54.0   NaN  46.0  27.0  95.0   NaN
2    1.0   4.0  39.0   NaN   NaN  53.0  76.0   5.0   NaN   NaN
3   33.0  71.0  21.0  55.0   7.0  20.0  50.0  34.0  71.0  92.0
4   23.0  41.0  36.0  29.0  96.0  44.0   NaN  44.0  72.0  26.0
5   27.0   NaN   NaN  38.0  50.0  90.0  48.0   NaN  60.0  71.0
6   41.0   NaN  88.0  16.0   3.0   NaN   NaN   NaN  98.0  25.0
7   84.0   NaN  55.0  85.0  69.0  72.0   NaN   NaN  80.0  13.0
8   53.0  14.0   NaN   3.0  86.0  86.0   NaN  89.0   NaN  94.0
9   84.0  92.0  32.0  77.0  95.0  74.0  90.0  85.0  76.0  53.0
10   NaN  96.0   NaN   NaN  38.0  26.0  54.0   NaN  52.0  99.0
11   NaN  54.0   NaN  58.0  85.0  63.0  64.0   NaN  53.0   NaN
12  15.0   NaN  90.0  49.0  30.0   NaN  87.0   NaN   5.0  42.0
13   NaN  97.0   NaN  60.0  41.0  16.0   NaN  26.0  43.0  41.0
14  39.0  79.0  99.0   6.0  73.0  92.0  18.0   NaN   9.0  15.0
15  68.0  95.0  69.0  45.0  10.0  12.0   4.0   NaN  41.0  10.0
16  55.0  76.0  69.0  71.0  44.0   NaN  22.0  32.0  59.0  19.0
17  63.0   8.0  68.0  50.0  12.0  89.0  57.0  35.0  69.0  95.0
18   NaN  25.0  10.0  84.0  11.0  54.0  34.0   NaN  13.0  17.0
19   NaN  86.0  73.0  23.0  85.0  51.0  94.0   1.0  93.0  96.0

In [102]:
df1.isna().sum().sum()

43

In [116]:
df1.dropna(subset=[0,3],axis=1)

0     2     3     4     5     6     7     8
0   48.0  20.0  29.0  35.0  44.0  38.0  50.0  83.0
1    NaN  31.0  42.0  54.0   NaN  46.0  27.0  95.0
2    1.0  39.0   NaN   NaN  53.0  76.0   5.0   NaN
3   33.0  21.0  55.0   7.0  20.0  50.0  34.0  71.0
4   23.0  36.0  29.0  96.0  44.0   NaN  44.0  72.0
5   27.0   NaN  38.0  50.0  90.0  48.0   NaN  60.0
6   41.0  88.0  16.0   3.0   NaN   NaN   NaN  98.0
7   84.0  55.0  85.0  69.0  72.0   NaN   NaN  80.0
8   53.0   NaN   3.0  86.0  86.0   NaN  89.0   NaN
9   84.0  32.0  77.0  95.0  74.0  90.0  85.0  76.0
10   NaN   NaN   NaN  38.0  26.0  54.0   NaN  52.0
11   NaN   NaN  58.0  85.0  63.0  64.0   NaN  53.0
12  15.0  90.0  49.0  30.0   NaN  87.0   NaN   5.0
13   NaN   NaN  60.0  41.0  16.0   NaN  26.0  43.0
14  39.0  99.0   6.0  73.0  92.0  18.0   NaN   9.0
15  68.0  69.0  45.0  10.0  12.0   4.0   NaN  41.0
16  55.0  69.0  71.0  44.0   NaN  22.0  32.0  59.0
17  63.0  68.0  50.0  12.0  89.0  57.0  35.0  69.0
18   NaN  10.0  84.0  11.0  54.0  34.0   NaN  13.0
19   NaN  73.0  23.0  85.0  51.0  94.0   1.0  93.0

In [129]:
df3 = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
.....: [np.nan, np.nan], [0.75, -1.3]],
.....: index=['a', 'b', 'c', 'd'],
.....: columns=['one', 'two'])
df3

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [133]:
df3.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [135]:
dframe = pd.DataFrame({'key1':['A']*2 + ['B']*3,
                    'key2': [2,2,2,3,3]})

In [136]:
dframe


key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [137]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [138]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [142]:
dframe.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [143]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})
df

brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [144]:
df.drop_duplicates()

brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [145]:
df.drop_duplicates(subset = ['brand'])

brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5

In [146]:
df.drop_duplicates(subset=['brand', 'style'], keep='last')

brand style  rating
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
4  Indomie  pack     5.0

In [148]:
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)

['apple', 'cherry']


In [149]:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

['banana', 'cherry', 'Kiwi', 'Orange']


In [150]:
def square(num):
    return num**2

In [151]:
my_nums = [1,2,3,4,5]

In [152]:
list(map(square,my_nums))

[1, 4, 9, 16, 25]

In [153]:
map(square,my_nums)